### ISSUE TITLE
Terminology section issues 

### ISSUE THREAD

**Issue by iherman** [w3c/did-use-cases#48] opened 2019-11-15 15:43 UTC
The fact of sharing the terminology section with the core spec does have some, possibly unwanted, consequences with references that are not relevant in the UCR document. As an example, it now says "The generic format of a DID is defined in this specification." I am sure there more. I guess what this means is that the language of the common terminology section should be revised to abide by the requirements of both documents.

However, there are elements that will remain no matter what:

- _From the use case document's perspective_, this section contains way too much details. I do not think any of the use cases really make use of, say, DID fragments, DID query, etc. and this presents further hurdles for the non-expert reader 
- the terminology should to include terms that the general reader may not know. For example, I must admit that, before joining this WG, I did not know the term "rotating" as used in the crypto world and a terminology entry would help. The same holds for, e.g., "pairwise-pseudonymous" and probably some others.

I must admit I am beginning to question the wisdom of sharing the terminology section. The audience of the two documents are fundamentally different, and these discrepancies show it...

**Comment by iherman** [comment] 2019-11-15 19:42
Actually... one way of handling the extra terms (like fragments) is to use use some html tricks. Ie, a term can be set of class, say, `spec-only` and set a`display: none` in the CSS of the use case document. This means we can continue to share the same terminology file but control what should really appear in for the user.

**Comment by jandrieu** [comment] 2019-11-15 19:54
Phil and I discussed the fragments and related terms. Those all stem from the use of DID-URL, which in turn mentions the rest. 

In this case, the reference to DID-URL will be removed. We just didn't have suitable replacement language for the FPWD.

That said, @iherman's other comments are still valid. We have work to do on the terms, both adding things like "rotate" as well as re-writing for suitability in both docs.

**Comment by jandrieu** [comment] 2020-06-03 18:34
Duplicate of #75

**Comment by philarcher** [comment] 2020-06-03 19:32
As this is a duplicate, we're closing this issue, but, conceptually, it remains open. Will need discussion in the whole group.

**Closed as completed by philarcher** 2020-06-03 19:32 UTC
Labels: duplicate, needs editor discussion
