### ISSUE TITLE
Describe relationship between DID Methods and DID Authentication in Use Cases document

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#13] opened 2019-10-29 06:08 UTC
There isn't a clear description of the relationship between DID Methods and the DID Authentication process in the Use Cases document.  Is the DID Authentication process entirely DID Method specific?  If not, is it possible to describe what parts of DID Authentication are and are not method-specific?

Also not made clear is the role of DID Methods in DID Resolution.  (Part of this might be productively covered in  the terminology section #12.)

While this may seem like basic stuff to those who have been developing these specs for a while, we owe it to readers and developers to make these relationships clear.  Knowing these things would help readers better understand the way that DIDs are intended to operate.

I'd also be interested in opinions what parts of these explanations belong in the Use Cases document versus which parts of them belong in (or also belong in) the DID Core spec.

**Comment by jandrieu** [comment] 2019-11-06 11:03
As discussed on the call today, authentication is intended to be method-independent, by design.

However, we can describe this more clearly, so I'm leaving this in as guidance for a post FPWD revision.

**Comment by philarcher** [comment] 2020-06-03 10:17
Looks to me as if a small amount of text could be added to https://w3c.github.io/did-use-cases/#authenticate to cover this point.

**Comment by jandrieu** [comment] 2020-06-03 20:00
Yes. I'll work on this.

**Comment by jandrieu** [comment] 2020-06-30 15:10
@selfissued We'd like to close this. Do you feel the current language around authentication is clear? Or do we need better language to address your concern?

**Comment by philarcher** [comment] 2020-07-15 19:31
@selfissued Do you have any further comment? If not, we'll close this in 7 days' time.

**Comment by jandrieu** [comment] 2020-07-29 19:31
Closing due to lack of further comment.

**Closed as completed by jandrieu** 2020-07-29 19:31 UTC
Labels: pending close
