### ISSUE TITLE
Relying Party terminology could confuse things

### ISSUE THREAD

**Issue by msporny** [w3c/did-use-cases#39] opened 2019-11-12 16:38 UTC
> A decentralized system will enable several key actions by three distinct entities: the Controller, the Relying Party, and the Subject.

We hit an issue with "Relying Party" in the Verifiable Credentials Working Group. That is special (highly specific) terminology in existing standards and I'm concerned that we don't mean the same thing here than what is expressed in current standards:

https://en.wikipedia.org/wiki/Relying_party

I suggest that we steer clear from that terminology and use a new term, or one that's broader than what's linked to above. I'm wondering if we can re-use **verifier** from the Verifiable Credentials spec..

**Comment by jandrieu** [comment] 2020-05-06 17:07
This is a duplicate of https://github.com/w3c/did-core/issues/248 

We should wait until there's a consensus on the term from the WG.

Did this get discussed on a recent call?

**Comment by philarcher** [comment] 2020-07-16 10:38
PR #84 has now been merged so that this issue can now be closed. Note the reference in that PR to the [WG resolution](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-06-30-did#resolution1) on 2020-06-30 to use Requesting Party.

**Closed as completed by philarcher** 2020-07-16 10:38 UTC
Labels: PR in review
